/**
 * TypeScript declaration file generator
 */

import type { ModelMetadata } from './crawler.js';
import {
  mapSpintaType,
  isRequired,
  modelPathToInterfaceName,
  sanitizePropertyName,
  generateJsDoc,
} from './typeMapper.js';

/**
 * Generate a TypeScript interface from model metadata
 */
function generateInterface(model: ModelMetadata): string {
  const interfaceName = modelPathToInterfaceName(model.path);
  const lines: string[] = [];

  // Add JSDoc
  const jsDoc = generateJsDoc(model.title, model.description);
  if (jsDoc !== '') {
    lines.push(jsDoc);
  }

  lines.push(`export interface ${interfaceName} {`);

  // Add base Spinta object properties
  lines.push('  /** Unique object identifier */');
  lines.push('  _id: string;');
  lines.push('  /** Model type path */');
  lines.push('  _type: string;');
  lines.push('  /** Object revision (for optimistic locking) */');
  lines.push('  _revision?: string;');
  lines.push('  /** Transaction ID */');
  lines.push('  _txn?: string;');

  // Add model properties
  for (const prop of model.properties) {
    const propName = sanitizePropertyName(prop.name);
    const tsType = mapSpintaType(prop.type);
    const required = isRequired(prop.type);
    const optional = required ? '' : '?';

    // Add property JSDoc
    const propJsDoc = generateJsDoc(prop.title, prop.description);
    if (propJsDoc !== '') {
      lines.push('');
      lines.push(
        propJsDoc
          .split('\n')
          .map((l: string) => '  ' + l)
          .join('\n')
      );
    }

    lines.push(`  ${propName}${optional}: ${tsType};`);
  }

  lines.push('}');

  return lines.join('\n');
}

/**
 * Generate a complete .d.ts file from model metadata
 */
export function generateDeclarationFile(
  models: readonly ModelMetadata[],
  namespace: string
): string {
  const lines: string[] = [];

  // File header
  lines.push('/**');
  lines.push(` * TypeScript definitions for ${namespace}`);
  lines.push(' * ');
  lines.push(' * Generated by lt-data-sdk CLI');
  lines.push(` * Generated at: ${new Date().toISOString()}`);
  lines.push(' * ');
  lines.push(' * @see https://get.data.gov.lt/' + namespace);
  lines.push(' */');
  lines.push('');

  // Generate each interface
  for (const model of models) {
    lines.push(generateInterface(model));
    lines.push('');
  }

  // Generate namespace map type for convenience
  if (models.length > 0) {
    lines.push('/**');
    lines.push(' * Map of all models in this namespace');
    lines.push(' * Use with SpintaClient for type-safe queries');
    lines.push(' */');
    lines.push('export interface ModelMap {');

    for (const model of models) {
      const interfaceName = modelPathToInterfaceName(model.path);
      lines.push(`  '${model.path}': ${interfaceName};`);
    }

    lines.push('}');
  }

  return lines.join('\n');
}
